nome : principal

em : [empurrar]

empregos :
  teste :
    roda em : ubuntu-mais recente

    passos :
      - execute : sudo apt-get install gifsicle graphicsmagick
      - usa : actions/checkout@v2.3.3
      - usa : actions/setup-node@v1.4.4
        com :
          versão do nó : 14

      - usa : bahmutov/npm-install@v1.4.3

      - correr : tipo de fio
      - correr : fio de fiapo
      - executar : teste de fio --ci

  benchmark de teste :
    roda em : ubuntu-mais recente

    passos :
      - execute : sudo apt-get install gifsicle graphicsmagick
      - usa : actions/checkout@v2.3.3
      - usa : actions/setup-node@v1.4.4
        com :
          versão do nó : 14

      - usa : bahmutov/npm-install@v1.4.3

      - executar : (pacotes de cd / criador de gif; benchmark yarn)

  ação-teste :
    roda em : ubuntu-mais recente
    necessidades : build-docker-image

    passos :
      - nome : gerar-jogo-cobra-de-grade-contribuição-do-github
        id : snake-gif
        usa : LeandroSilvaLara / LeandroSilvaLara @ master
        com :
          github_user_name : LeandroSilvaLara
          gif_out_path : dist / github-Contribution-grid-snake.gif
          svg_out_path : dist / github-Contribution-grid-snake.svg

      - nome : certifique-se de que o arquivo gerado existe
        correr : |
          ls -l $ {{steps.snake-gif.outputs.gif_out_path}}
          test -f $ {{steps.snake-gif.outputs.gif_out_path}}
      - usa : crazy-max/ghaction-github-pages@v2.1.3
        com :
          target_branch : output
          build_dir : dist
        env :
          GITHUB_TOKEN : $ {{secrets.MY_GITHUB_TOKEN_GH_PAGES}}

  deploy-ghpages :
    roda em : ubuntu-mais recente
    passos :
      - usa : actions/checkout@v2.3.3
      - usa : actions/setup-node@v1.4.4
        com :
          versão do nó : 14

      - usa : bahmutov/npm-install@v1.4.3

      - run : yarn build: demo
        env :
          GITHUB_USER_CONTRIBUTION_API_ENDPOINT : https://snk-one.vercel.app/api/github-user-contribution/

      - usa : crazy-max/ghaction-github-pages@v2.1.3
        if : success () && github.ref == 'refs / heads / master'
        com :
          target_branch : gh-pages
          build_dir : packages / demo / dist
        env :
          GITHUB_TOKEN : $ {{secrets.MY_GITHUB_TOKEN_GH_PAGES}}

  build-docker-image :
    roda em : ubuntu-mais recente
    passos :
      - usa : actions/checkout@v2.3.3
      - usa : actions/setup-node@v1.4.4
        com :
          versão do nó : 14

      - usa : bahmutov/npm-install@v1.4.3

      - run : yarn build: action

      - usa : docker / setup-qemu-action @ v1

      - usa : docker / setup-buildx-action @ v1

      - usa : docker / login-action @ v1
        com :
          nome de usuário : $ {{secrets.DOCKERHUB_USERNAME}}
          senha : $ {{secrets.DOCKERHUB_TOKEN}}

      - usa : docker / build-push-action @ v2
        id : docker_build
        com :
          push : $ {{github.ref == 'refs / heads / master'}}
          tags : |
            LeandroSilvaLara / LeandroSilvaLara: mais recente
            LeandroSilvaLara / LeandroSilvaLara: $ {{github.sha}}
          arquivo : packages / action / Dockerfile
          contexto : pacotes / ação
